import { StyleSheet } from 'react-native';

// Professional jade green color palette
export const colors = {
  background: '#141416',
  backgroundDark: '#0c0c0e',
  primary: '#00a878',
  primaryMuted: 'rgba(0, 168, 120, 0.75)',
  primaryDim: 'rgba(0, 168, 120, 0.12)',
  primaryBorder: 'rgba(0, 168, 120, 0.22)',
  cardBg: 'rgba(0, 168, 120, 0.07)',
  cardBorder: 'rgba(0, 168, 120, 0.18)',
  white: '#f5f5f5',
  textMuted: 'rgba(255, 255, 255, 0.65)',
  textDim: 'rgba(255, 255, 255, 0.4)',
  fieldGreen: '#1a3830',
  fieldGreenLight: '#264a40',
  fieldGreenDark: '#122822',
};

export default StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    backgroundColor: colors.backgroundDark,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryBorder,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: colors.white,
    letterSpacing: 1,
  },
  headerSubtitle: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '700',
    letterSpacing: 3,
    marginTop: 4,
  },
  viewToggleRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  toggleButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  toggleButtonInactive: {
    backgroundColor: 'transparent',
    borderColor: colors.primaryBorder,
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 1,
  },
  toggleButtonTextActive: {
    color: colors.backgroundDark,
  },
  toggleButtonTextInactive: {
    color: colors.primary,
  },
  field: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: colors.fieldGreen,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.fieldGreenLight,
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 16,
    alignSelf: 'center',
    maxWidth: 400,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 8,
  },
  pressed: {
    opacity: 0.7,
    transform: [{ scale: 0.95 }],
  },
  circleText: {
    fontWeight: '800',
    color: colors.white,
    fontSize: 10,
  },
  posLabel: {
    marginTop: 6,
    fontSize: 10,
    textAlign: 'center',
    width: 80,
    color: colors.white,
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  dialogList: {
    maxHeight: 300,
  },
  rosterContainer: {
    paddingHorizontal: 16,
    justifyContent: 'flex-end',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.white,
    marginBottom: 12,
    letterSpacing: 0.5,
  },
  sortRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  sortButton: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginRight: 8,
    borderWidth: 1.5,
  },
  sortButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  sortButtonInactive: {
    backgroundColor: 'transparent',
    borderColor: colors.primaryBorder,
  },
  sortButtonText: {
    fontSize: 12,
    fontWeight: '700',
  },
  sortButtonTextActive: {
    color: colors.backgroundDark,
  },
  sortButtonTextInactive: {
    color: colors.primary,
  },
  rosterScroll: {
    paddingVertical: 12,
    alignItems: 'flex-end',
  },
  playerCard: {
    alignItems: 'center',
    width: 85,
    marginRight: 12,
    paddingVertical: 8,
    paddingHorizontal: 8,
    backgroundColor: colors.cardBg,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    maxHeight: 90,
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  playerIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryDim,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.primary,
    marginBottom: 4,
  },
  playerNumber: {
    fontWeight: '800',
    color: colors.white,
    fontSize: 10,
  },
  playerName: {
    marginBottom: 8,
    fontSize: 10,
    textAlign: 'center',
    color: colors.white,
    fontWeight: '600',
  },
  metricText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: '700',
    marginTop: 4,
  },
  posLabelTop: {
    marginBottom: 6,
    fontSize: 12,
    textAlign: 'center',
    width: 90,
    color: colors.textMuted,
  },
  assignedText: {
    fontSize: 10,
    color: colors.primary,
    marginTop: 4,
    fontWeight: '600',
    backgroundColor: colors.primaryDim,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  battingContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  battingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  battingList: {
    flex: 1,
    maxHeight: 300,
  },
  battingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  battingIndex: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  battingIndexText: {
    color: colors.backgroundDark,
    fontWeight: '800',
    fontSize: 14,
  },
  battingPlayerInfo: {
    flex: 1,
  },
  battingPlayerName: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '700',
  },
  battingPlayerStats: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  actionButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginLeft: 8,
  },
  actionButtonPrimary: {
    backgroundColor: colors.primary,
  },
  actionButtonSecondary: {
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: colors.primaryBorder,
  },
  actionButtonText: {
    fontWeight: '700',
    fontSize: 13,
  },
  actionButtonTextPrimary: {
    color: colors.backgroundDark,
  },
  actionButtonTextSecondary: {
    color: colors.primary,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    backgroundColor: colors.backgroundDark,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
    overflow: 'hidden',
  },
  modalHeader: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: colors.primaryBorder,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: colors.white,
  },
  modalSubtitle: {
    fontSize: 12,
    color: colors.primary,
    marginTop: 4,
    fontWeight: '600',
  },
  modalBody: {
    padding: 16,
  },
  modalFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.primaryBorder,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  listItemDisabled: {
    opacity: 0.5,
  },
  listItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primaryDim,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
  },
  listItemContent: {
    flex: 1,
  },
  listItemTitle: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '700',
  },
  listItemDescription: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
  },
  statLabel: {
    color: colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  statValue: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '800',
  },
  divider: {
    height: 1,
    backgroundColor: colors.primaryBorder,
    marginVertical: 16,
    marginHorizontal: 16,
  },
});
